{% set name = "ipython-sql" %}
{% set version = "0.3.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: ipython-sql-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7187f6371f38b89d8fb63c2c7c4233d9000fb53b460dae79e4a359df366cc3ed
  patches:
    # Use io.open in py27
    - github__sodre__ipython-sql__py27-setup.patch   # [py27]

build:
  number: 1002
  script: 
    - python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python
    - prettytable
    - ipython >=1.0  # [not win]
    - ipython >=1.0  # [win and not py35]
    - ipython >=1.0,<5  # [win and py35]
    - ipython_genutils >=0.1.0
    - sqlalchemy >=0.6.7
    - sqlparse
    - six

test:
  imports:
    - sql

about:
  home: https://pypi.python.org/pypi/ipython-sql
  license: MIT
  license_file: LICENSE
  summary: 'RDBMS access via IPython'

  description: 'ipython-sql introduces a %sql (or %%sql) magic to your notebook allowing you to
    connect to a database, using SQLAlchemy connect strings, then issue SQL commands within 
    IPython or IPython Notebook.'
  dev_url: https://github.com/catherinedevlin/ipython-sql

extra:
  recipe-maintainers:
    - sodre
